# Object Creation
## Creating a Series by passing a list of values, letting pandas create adefault integer index:

```{python}
import numpy as np
import pandas as pd
pd.Series([1, 2, 5, np.nan, 8])
```
## Creating a DataFrame by passing a numpy array, with a datetime index and labeled columns:
```{python}
dates = pd.date_range('20130101', periods=6)
df = pd.DataFrame(np.random.randn(6,4),index=dates,columns=list("ABCD"))
```
## Creating a DataFrame by passing a dict of objects that can be converted to series-like:
```{python}
df2=pd.DataFrame({'A':1.,
                  'B':pd.Timestamp('20130102'),
                  'C':pd.Series(1,index=list(range(4)),dtype='float32')
                  })
                  help(pd.Timestamp)
```
# selection
## 使用标签（label）选取：.loc[ ]
```{python}
df2 = pd.DataFrame(np.random.randn(5,4), columns=list('ABCD'),index=pd.date_range('20130101',periods=5))
df2.loc['20130102':'20130104']
df.loc[:,['A','B']]
```
## 使用位置选取：.iloc[ ]
```{python}
df2.iloc[2]#表示第三行
df2.iloc[2,3]#表示第三行第四列的数
df2.iloc[[0,2,4]]#表示第1，第3，第5行
df2.iloc[[0,2,4], :3]#表示第1，第3，第5行的前3列

## DataFrame.at 和 DataFrame.iat
```{python}
df2.at['A',2013-01-01]#获取指定行/列对的值
df2.iat[0,0]
```

```
## Boolean indexing(逻辑值下标)
```{python}
df2[df2.A>0]
df2[df2>0]#对整个表格进行筛选
df2.loc[df2['A']>0,'A':'C']
df2.iloc[list(df2.A>0),0:3]
```

### Indexing with isin
```{python}
s=pd.Series(np.arange(5),index=np.arange(5)[::-1],dtype='int64')
s[s.isin([2,4,6])]#isin返回布尔值

df=pd.DataFrame({'Vars':[1,2,3,4],'ids':['a','b','f','n'],'ids2': ['a', 'n', 'c', 'n']})
values=['a','b',1,3]
df.isin(values)

#  match certain values with certain columns.
values = {'ids': ['a', 'b'], 'vals': [1, 3]}
df.isin(values)

values = {'ids': ['a', 'b'], 'ids2': ['a', 'c'], 'vals': [1,
3]}
row_mask = df.isin(values).all(1)
df[row_mask]

### where所得结果可以与原数据保持一致
s[s>0]
s.where(s>0)
df2.where(df2<0,-df2)#df.where(condition,other)
help(df.where)
```
# Duplicate Data,识别数据框有没有重复的行
```{python}
df2 = pd.DataFrame({'a': ['one', 'one', 'two', 'two', 'two', 'three', 'four'],
'b': ['x', 'y', 'x', 'y', 'x', 'x', 'x'],
'c': np.random.randn(7)})
df2.duplicated('a')
df2.duplicated('a', keep='last')
df2.duplicated('a', keep=False)#所有重复值
df2.drop_duplicates('a')
df2.drop_duplicates('a', keep='last')
df2.drop_duplicates('a', keep=False)
 ### pass a list of columns to identify duplications.
df2.duplicated(['a', 'b'])
df2.drop_duplicates(['a', 'b'])
```

# missing data
```{python}
df2.dropna(how='any')
```

# merge
```{python}
## concat
df=pd.DataFrame(np.random.randn(10,4))
pieces=[df[:3],df[3:7],df[7:]]
pd.concat(pieces)
## appdend
df = pd.DataFrame(np.random.randn(8, 4), columns=['A','B','C','D'])
s=df.iloc[3]
df.append(s)#报错
df.append(s, ignore_index=True)
```

# Group By: split-apply-combine
```{python}
df = pd.DataFrame({'A': ['foo', 'bar', 'foo', 'bar',
'foo', 'bar', 'foo', 'foo'],
'B': ['one', 'one', 'two', 'three',
'two', 'two', 'one', 'three'],
'C': np.random.randn(8),
'D': np.random.randn(8)})

df.groupby('A').sum()
df.groupby(['A','B']).sum()
df.groupby(['A','B']).agg([np.sum,np.mean,np.std])
df.groupby(['A','B']).agg({'C' : np.sum,'D' : np.std})
```

# group plotting
```{python}
import matplotlib.pyplot as plt
np.random.seed(1234)
df = pd.DataFrame(np.random.randn(50, 2))
df['g'] = np.random.choice(['A', 'B'], size=50)
df.loc[df['g'] == 'B', 1] += 3
df.groupby('g').boxplot()
```

# 使用pivot()方法
```{python}
import pandas.util.testing as tm;tm.N=3
def unpivot(frame):
    N,K=frame.shape
    data={'value' : frame.values.ravel('F'),
    'variable' : np.asarray(frame.columns).repeat(N),
    'date' : np.tile(np.asarray(frame.index), K)}
    return pd.DataFrame(data,columns=['date','variable','value'])
df = unpivot(tm.makeTimeDataFrame())
df[df['variable']=='A']
df.pivot(index='date',columns='variable',values='value')
df['value2'] = df['value']*2
df.pivot('date', 'variable')
pivoted = df.pivot('date', 'variable')
pivoted['value2']

help(tm.makeTimeDataFrame)

df = pd.DataFrame({"A": ["foo", "foo", "foo", "foo", "foo",
 "bar", "bar", "bar", "bar"],
 "B": ["one", "one", "one", "two", "two",
"one", "one", "two", "two"],
 "C": ["small", "large", "large", "small",
 "small", "large", "small", "small",
 "large"],
"D": [1, 2, 2, 3, 3, 4, 5, 6, 7],
"E": [2, 4, 5, 5, 6, 6, 8, 9, 9]})

table = pd.pivot_table(df, values='D', index=['A', 'B'],
columns=['C'], aggfunc=np.sum)

table = pd.pivot_table(df, values=['D', 'E'], index=['A', 'C'],
aggfunc={'D': np.mean,
 'E': np.mean})

table = pd.pivot_table(df, values=['D', 'E'], index=['A', 'C'],
aggfunc={'D': np.mean,
'E': [min, max, np.mean]})

# Cross tabulations使用交叉表函数来计算两个（或多个）因子的交叉表。
```{python}
foo, bar, dull, shiny, one, two = 'foo', 'bar', 'dull', 'shiny', 'one', 'two'
a = np.array([foo, foo, bar, bar, foo, foo], dtype=object)
b = np.array([one, one, two, one, two, one], dtype=object)
c = np.array([dull, dull, shiny, dull, dull, shiny], dtype=
object)
pd.crosstab(a, [b, c], rownames=['a'], colnames=['b', 'c'])

df = pd.DataFrame({'A': [1, 2, 2, 2, 2], 'B': [3, 3, 4, 4, 4],
'C': [1, 1, np.nan, 1, 1]})
pd.crosstab(df.A, df.B)
pd.crosstab(df['A'], df['B'], normalize=True)
pd.crosstab(df['A'], df['B'], normalize='columns')
pd.crosstab(df.A, df.B, values=df.C, aggfunc=np.sum, normalize=
True,margins=True)
```

# cut function连续数据离散化或分组
```{python}
ages = np.array([10, 15, 13, 12, 23, 25, 28, 59, 60])
pd.cut(ages, bins=3)
pd.cut(ages, bins=[0, 18, 35, 70])
```

# dummy variables: get_dummies()分类变量编码
```{python}
df = pd.DataFrame({'key': list('bbacab'), 'data1': range(6)})
pd.get_dummies(df['key'])#只得到编码列
dummies = pd.get_dummies(df['key',prefix='key')

df = pd.DataFrame({'A': ['a', 'b', 'a'], 'B': ['c', 'c', 'b'],
'C': [1, 2, 3]})
pd.get_dummies(df, columns=['A'])#表示对列'A'进行编码，得到的结果包括所有列
```

# 其他函数-创建分类
```{python}
s = pd.Series(["a","b","c","a"], dtype="category")
df = pd.DataFrame({"id":[1,2,3,4,5,6], "raw_grade":['a', 'b', 'b', 'a', 'a', 'e']})
df["grade"] = df["raw_grade"].astype("category")
df["grade"].cat.categories = ["very good", "good", "very bad"]
df["grade"] = df["grade"].cat.set_categories(["very bad", "bad"
, "medium", "good", "very good"])

df.sort_values(by="grade")
df.groupby("grade").size()
```

# 画图
```{python}
ts = pd.Series(np.random.randn(1000), index=pd.date_range('1/1/2000',periods=1000))
ts = ts.cumsum()
ts.plot()

df3 = pd.DataFrame(np.random.randn(1000, 2), columns=['B', 'C'
]).cumsum()
df3['A'] = pd.Series(list(range(len(df3))))

df3.plot(x='A', y='B')
```