
# 100 numpy exercises with hint

This is a collection of exercises that have been collected in the numpy mailing
list, on stack overflow and in the numpy documentation. I've also created some
to reach the 100 limit. The goal of this collection is to offer a quick
reference for both old and new users but also to provide a set of exercises for
those who teach.

If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆) 

(**hint**: import … as …)

```{python}
import numpy as np
```

#### 2. Print the numpy version and the configuration (★☆☆) 

(**hint**: np.\_\_version\_\_, np.show\_config)

```{python}
np.__version__
```


#### 3. Create a null vector of size 10 (★☆☆) 

(**hint**: np.zeros)

```{python}
x = np.zeros(10)
print(x)
```


#### 4.  How to find the m array (★☆☆) emory size of any

(**hint**: size, itemsize)

```{python}
x.size
x.itemsize
```


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 

(**hint**: np.info)

```{python}
np.info(np.add)
```


#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 

(**hint**: array\[4\])

```{python}
x[4] = 1
print(x)
```


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 

(**hint**: np.arange)

```{python}
x = np.arange(10, 50)
print(x)
```

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 

(**hint**: array\[::-1\])

```{python}
print(x[::-1])
```


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 

(**hint**: reshape)

```{python}
x = np.arange(9).reshape((3, 3))
print(x)
```


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 

(**hint**: np.nonzero)

```{python}
x = np.array([1,2,0,0,4,0])
print(np.nonzero(x))
```


#### 11. Create a 3x3 identity matrix (★☆☆) 

(**hint**: np.eye)

```{python}
print(np.eye(3))
print(np.identity(3))
```


#### 12. Create a 3x3x3 array with random values (★☆☆) 

(**hint**: np.random.random)

```{python}
print(np.random.random((3, 3, 3)))
```


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 

(**hint**: min, max)

```{python}
x = np.random.randn(10, 10)
print(x.max(), x.min())
```


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 

(**hint**: mean)

```{python}
x = np.random.random(30)
x.mean()
```


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 

(**hint**: array\[1:-1, 1:-1\])

```{python}
x = np.ones((3, 3))
x[1:-1, 1:-1] = 0
print(x)
```


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 

(**hint**: np.pad)

 ```{python}
x = np.random.randn(3, 3)
print(np.pad(x, 1, 'constant'))
```


#### 17. What is the result of the following expression? (★☆☆) 

(**hint**: NaN = not a number, inf = infinity)

```{python}
0 * np.nan #np.nan
np.nan == np.nan #Fales
np.inf > np.nan #False
np.nan - np.nan #np.nan
np.nan in set([np.nan]) #True
0.3 == 3 * 0.1 #False 浮点数可以比大小，但相等要用isclose比较
np.isclose(0.3, 3 * 0.1)
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 

(**hint**: np.diag)

```{python}
print(np.diag([1, 2, 3, 4], -1))
```

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 

(**hint**: array\[::2\])

```{python}
x = np.zeros((8, 8))
x[::2, ::2] = 1
x[1::2, 1::2] = 1
print(x)
```


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 

(**hint**: np.unravel\_index)

```{python}
print(np.unravel_index(100, (6, 7, 8)))
```

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 

(**hint**: np.tile)

```{python}
x = np.array([[1, 0], [0, 1]])
print(np.tile(x, (4, 4)))
```


#### 22. Normalize a 5x5 random matrix (★☆☆) 

(**hint**: (x - mean) / std)

```{python}
x = np.random.random((5, 5))
x = (x - x.mean())/x.std()
print(x)
```


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 

(**hint**: np.dtype)

```{python}
print(np.dtype([('R', np.ubyte), ('G', np.ubyte),
('B', np.ubyte), ('A', np.ubyte)]))
```


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 

(**hint**: np.dot | @)

```{python}
a = np.random.randn(5, 3)
b = np.random.normal(size=(3, 2))
print(np.dot(a ,b))
```



#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 

(**hint**: >, <=)

```{python}
x = np.arange(12)
x[(x > 3) & (x < 8)] *= -1
print(x)
```



#### 26. What is the output of the following script? (★☆☆) 

(**hint**: np.sum)



```{python}
# Author: Jake VanderPlas
print(sum(range(5),-1))
print(np.sum(range(5),-1))#-1代表轴

```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)


```{python}
Z = np.arange(6)
Z**Z
2 << Z >> 2 #对二进制数进行移位操作
Z <- Z
1j*Z
Z/1/1
Z<Z>Z #ValueError
```

#### 28. What are the result of the following expressions?


```{python}
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆) 

(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

```{python}
x = np.random.uniform(-1, 1, size=(3, 3))
print(np.ceil(np.abs(x)))
print(np.ceil(np.copysign(x, np.ones((3, 3)))))
```


#### 30. How to find common values between two arrays? (★☆☆) 

(**hint**: np.intersect1d)

```{python}
x = np.arange(6)
y = np.arange(4, 8)
print(np.intersect1d(x, y))
print([val for val in x if val in y])
```


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 

(**hint**: np.seterr, np.errstate)

```{python}
defaults = np.seterr(all='ignore')
```


#### 32. Is the following expressions true? (★☆☆) 

(**hint**: imaginary number)

```{python}
np.sqrt(-1) == np.emath.sqrt(-1)
print(np.sqrt(-1))
print(np.emath.sqrt(-1))
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 

(**hint**: np.datetime64, np.timedelta64)

```{python}
today = np.datetime64('today')
yesterday = np.datetime64('today') - np.timedelta64(1)
tomorrow = np.datetime64('today') + np.timedelta64(1)
print(today, yesterday, tomorrow)
```


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 

(**hint**: np.arange(dtype=datetime64\['D'\]))

```{python}
x = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(x)
```

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆) 

(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

```{python}
A = np.ones(3)
B = np.ones(3)
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(B, A, out=A)
print(A)
```

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 

(**hint**: %, np.floor, np.ceil, astype, np.trunc)

```{python}
x = np.random.uniform(0, 5, (4, 4))
print(x)
print(np.floor(x))
print(np.ceil(x) - 1)
print(np.trunc(x))
print(x - x%1)
print(x // 1)
print(x.astype(int))
```

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 

(**hint**: np.arange)

```{python}
print(np.tile(np.arange(5), (5, 1)))
print(np.repeat(np.arange(5).reshape(1, -1), 5, axis=0))
```

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 

(**hint**: np.fromiter)

```{python}
print(np.fromiter(range(10), int))
```

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 

(**hint**: np.linspace)

```{python}
print(np.linspace(0, 1, 11, endpoint=False)[1:])
```


#### 40. Create a random vector of size 10 and sort it (★★☆) 

(**hint**: sort)

```{python}
a = np.random.randn(10)
print(np.sort(a))
```


#### 41. How to sum a small array faster than np.sum? (★★☆) 

(**hint**: np.add.reduce)

```{python}
a = np.arange(10)
print(np.add.reduce(a))
```


#### 42. Consider two random array A and B, check if they are equal (★★☆) 

(**hint**: np.allclose, np.array\_equal)

```{python}
A = np.array([1, 2])
B = np.array([1, 2.00000001])
np.allclose(A, B)
np.array_equal(A, B)
```


#### 43. Make an array immutable (read-only) (★★☆) 

(**hint**: flags.writeable)

```{python}
x = np.zeros(10)
x.flags.writeable = False
```

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 

(**hint**: np.sqrt, np.arctan2)

```{python}
cart = np.random.random((10, 2))

polar = np.column_stack((np.sqrt(np.add.reduce(np.square(cart), axis=1)), np.arctan(np.divide.reduce(cart, axis=1))))
print(cart, '\n\n', polar)

Z = cart
X, Y = Z[:, 0], Z[:, 1]
R = np.sqrt(X ** 2 + Y ** 2)
T = np.arctan2(Y, X) # arctan2 和 archtan的区别
print(np.column_stack((R, T)))
```


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 

(**hint**:  )

```{python}
z = np.arange(16)
z[np.argmax(z)] = 0
print(z)
```


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 

(**hint**: np.meshgrid)

```{python}
xx, yy = np.meshgrid(np.linspace(0, 1, 10), np.linspace(0, 1, 10))
print(xx, yy)
```


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 

(**hint**: np.subtract.outer)

```{python}
X = np.random.rand(2, 2)
Y = np.random.randn(2, 2)
C = 1 / np.subtract.outer(X, Y)
print(np.linalg.det(C))
```


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 

(**hint**: np.iinfo, np.finfo, eps)

```{python}
print(np.iinfo(np.int64))
print(np.iinfo(np.int32))
print(np.iinfo(np.uint16))
print(np.finfo(np.float64))
print(np.finfo(np.float16))
```


#### 49. How to print all the values of an array? (★★☆) 

(**hint**: np.set\_printoptions)

```{python}
print(np.eye(10))
np.set_printoptions(threshold=1600)
print(np.eye(40))
```


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 

(**hint**: argmin)

```{python}
sample50 = np.random.rand(4, 3) * 10
print(sample50)
print(np.argmin(sample50))
print(np.argmin(sample50, axis=0))
print(np.argmin(sample50, axis=1))
print(np.unravel_index(np.argmin(sample50), sample50.shape))

Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v).argmin())
print(Z[index])
```


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 

(**hint**: dtype)

```{python}
mydtype = np.dtype([('position', [('x', np.int8), ('y', np.int8)])
              ,('color', [('r', np.int16), ('g', np.int16),('b', np.int16)])])
print(np.zeros((2, 3), mydtype))
```


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 

(**hint**: np.atleast\_2d, T, np.sqrt)

```{python}
x = np.random.random((100, 2))
x1, x2 = np.atleast_2d(x[:,0], x[:,1])
dist = np.sqrt((x1-x1.T)**2 + (x2-x2.T)**2)
print(dist)
```

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 

(**hint**: view and [:] = )

```{python}
x = np.arange(10, dtype=np.int32)
x = x.astype(np.float32, copy=False)
print(x)
```

#### 54. How to read the following file? (★★☆) 

(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```
```{python}
from io import StringIO

s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                ,  , 9,10,11\n""") 
print(np.genfromtxt(s,delimiter=','))
```
#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 

(**hint**: np.ndenumerate, np.ndindex)

```{python}
a = np.array([[1, 2], [3, 4]])
for index, x in np.ndenumerate(a):
    print(index, x)
for index in np.ndindex(a.shape):
    print(index)
```

#### 56. Generate a generic 2D Gaussian-like array (★★☆) 

(**hint**: np.meshgrid, np.exp)

```{python}
X, Y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
Z = np.sqrt(X*X + Y*Y)
mu, sigma = 0, 1
G = np.exp(-(Z - mu)**2/(2*sigma**2))
print(G)
```

#### 57. How to randomly place p elements in a 2D array? (★★☆) 

(**hint**: np.put, np.random.choice)

```{python}
p = 15
x = np.zeros((3, 10))
np.put(x, np.random.choice(range(3*10), 5), p)
print(x)
```

#### 58. Subtract the mean of each row of a matrix (★★☆) 

(**hint**: mean(axis=,keepdims=))

```{python}
x = np.arange(16).reshape(4, 4)
me = x.mean(axis=1, keepdims=True)
y = x - me
print(y)
```

#### 59. How to sort an array by the nth column? (★★☆) 

(**hint**: argsort)

```{python}
z = np.random.randint(0, 10, (3, 3))
print(np.argsort(z, axis=0))
```

#### 60. How to tell if a given 2D array has null columns? (★★☆) 

(**hint**: any, ~)

```{python}
Z = np.random.randint(0,3,(3,20))
print((~Z.any(axis=0)).any())
```

#### 61. Find the nearest value from a given value in an array (★★☆) 

(**hint**: np.abs, argmin, flat)

```{python}
x = np.random.random((3, 3))
m = 0.5
print(x.ravel()[(np.abs(x) - m).argmin()])
```


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 

(**hint**: np.nditer)

```{python}
x = np.random.normal(size=(3, 1))
y = x.T
for x, y, z in np.nditer([x, y, None]):
    z[...] = x + y
print(z)
```


#### 63. Create an array class that has a name attribute (★★☆) 

(**hint**: class method)

```{python}
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        if obj is None:return
        self.info = getattr(obj, 'name', "no name")
Z = NamedArray(np.arange(10), "range_10")
print (Z.name)
```

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 

(**hint**: np.bincount | np.add.at)

```{python}
x = np.ones(10)
m = np.random.randint(0, len(x), 20)
print(m)
x_ = x + np.bincount(m, minlength=len(x))
print(x_)

np.add.at(x, m, 1)
print(x)
```

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 

(**hint**: np.bincount)

```{python}
X = np.arange(5)
I = [3, 9, 4, 2, 0]
F = np.bincount(I, X)
print(F)
```

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 

(**hint**: np.unique)

```{python}
w, h = 16, 16
I = np.random.randint(0, 2,(h, w, 3)).astype(np.ubyte)
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)
```


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 

(**hint**: sum(axis=(-2,-1)))

```{python}
x = np.random.randn(100).reshape((5, 5, 2, 2))
print(np.sum(x, axis=(-2,-1)))
```


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 

(**hint**: np.bincount)

```{python}
D = np.random.randn(100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)
```

#### 69. How to get the diagonal of a dot product? (★★★) 

(**hint**: np.diag)

```{python}
x = np.array([[1, 2], [3, 5]])
y = x.T
print(np.diag(np.dot(x, y)))
```


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 

(**hint**: array[::4])

```{python}
x = np.array([1, 2, 3, 4, 5])
h = 3
y = np.zeros(x.size + 4*h)
y[::h+1] = x
print(y)
```


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 

(**hint**: array[:, :, None])

```{python}
x = np.random.random((5, 5, 3))
y = np.random.random((5, 5))
print(x * y[:, :, None])
```

#### 72. How to swap two rows of an array? (★★★) 

(**hint**: array[[]] = array[[]])

```{python}
x = np.arange(12).reshape((4, 3))
x[[1, 3]] = x[[3, 1]]
print(x)
```

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 

(**hint**: repeat, np.roll, np.sort, view, np.unique)

```{python}
x = np.random.randint(0, 10, (10, 3))
F = np.roll(x.repeat(2, axis=1), -1, axis=1)  
F = F.reshape(len(F) * 3, 2)
F = np.sort(F, axis=1)
G = F.view(dtype=[('p0', F.dtype), ('p1', F.dtype)])
G = np.unique(G)
print(G)
```


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 

(**hint**: np.repeat)

```{python}
C = np.array([0, 2, 1, 3, 0, 0, 1])
A = np.array([])
for i, c in enumerate(C):
    A = np.append(A, np.ones(c)*(i))
A = A.astype(int)   
print(A)
print((np.bincount(A) == C).all())
```



#### 75. How to compute averages using a sliding window over an array? (★★★) 

(**hint**: np.cumsum)

```{python}
def sliding(a, n=3):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(10)
print(sliding(Z, n=3))
```

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 

(**hint**: from numpy.lib import stride\_tricks)

```{python}
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)
```

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 

(**hint**: np.logical_not, np.negative)

```{python}
x = np.random.randint(0, 2, 50)
print(np.logical_not(x))

y = np.random.uniform(-1, 1, 100)
print(np.negative(y))
```

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

```{python}
A = np.array([[1, 2], [1, 2], [1, 3], [1, 2]])
B = np.array([[2, 1], [2, 2], [3, 1], [3, 2]])
C = np.array([1.2, 1.2])

print(np.abs(np.cross(A - C, B - C, axis=1)) / np.linalg.norm(A - B, axis=1))
```


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

```{python}
def distance(P0, P1, p):
    T = P1 - P0
    L = (T ** 2).sum(axis=1)
    U = -((P0[:, 0] - p[..., 0]) * T[:, 0] + (P0[:, 1] - p[..., 1]) * T[:, 1]) / L
    U = U.reshape(len(U), 1)
    D = P0 + U * T - p
    return np.sqrt((D ** 2).sum(axis=1))
P0 = np.random.uniform(-10, 10, (10, 2))
P1 = np.random.uniform(-10, 10, (10, 2))
p = np.random.uniform(-10, 10, (10, 2))
print(np.array([distance(P0, P1, p_i) for p_i in p]))
```

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 

(**hint**: minimum, maximum)

```{python}

```


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 

(**hint**: stride\_tricks.as\_strided)

```{python}
from numpy.lib import stride_tricks #同76题
Z = np.arange(1, 15)
R = stride_tricks.as_strided(Z, shape=(11, 4), strides=(4, 4))
#strides:跨越数组各个维度所需要经过的字节数（bytes）
print(R)
```

#### 82. Compute a matrix rank (★★★) 

(**hint**: np.linalg.svd)

```{python}
x = np.eye(4)
out1 = np.linalg.matrix_rank(x)
out2 = np.linalg.svd(x)[1].size
print(out1, out2)
```

#### 83. How to find the most frequent value in an array? 

(**hint**: np.bincount, argmax)

```{python}
x = np.random.randint(0, 5, 200)
#np.bincount返回0，1， 2...计数， argmax返回最大值的索引（也就是对应的值）
print(np.bincount(x).argmax())
```

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 

(**hint**: stride\_tricks.as\_strided)

```{python}
x = np.random.rand(10, 10)
strides = x.strides + x.strides
y = stride_tricks.as_strided(x, (8, 8, 3, 3), strides)
print(y)
```

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 

(**hint**: class method)

```{python}
class Symtric(np.ndarray):
    def __setitem__(self, key, value):
        i, j = key
        super(Symtric, self).__setitem__((i, j), value)
        super(Symtric, self).__setitem__((j, i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symtric)

S = symetric(np.random.randint(0, 10, (5, 5)))
S[0, 0] = 42
print(S)
```

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 

(**hint**: np.tensordot)

```{python}
p, n = 5, 10
x = np.ones((p, n, n))
y = np.ones((p, n, 1))
z = np.tensordot(x, y, axes=[[0, 2], [0, 1]])
print(z)
```

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 

(**hint**: np.add.reduceat)

```{python}
Z = np.random.choice(100,(16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),np.arange(0, Z.shape[1], k), axis=1)
print(S)
```

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

```{python}

```

#### 89. How to get the n largest values of an array (★★★) 

(**hint**: np.argsort | np.argpartition)

```{python}
n = 10
x = np.random.rand(100)
print(x[np.argsort(x)[-n:]])

print(x[np.argpartition(-x, n)[:n]])
```

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 

(**hint**: np.indices)

```{python}
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix
print(cartesian(([1, 2, 3], [4, 5], [6, 7])))
```

#### 91. How to create a record array from a regular array? (★★★) 

(**hint**: np.core.records.fromarrays)

```{python}
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, names='列1,列2,列3', formats='S8,f8,i8')
print(R)
```

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 

(**hint**: np.power, \*, np.einsum)

```{python}
Z = np.random.rand(100, 100)
print(np.power(Z, 3))
print(Z**3)
print(Z*Z*Z)
```

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 

(**hint**: np.where)

```{python}
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)
```

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

```{python}
x = np.random.choice(3, (10, 3))
y = x[x.max(axis=1) != x.min(axis=1), :]  
print(y)
```

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 

(**hint**: np.unpackbits)

```{python}
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))
```

#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 

(**hint**: np.ascontiguousarray | np.unique)

```{python}
x = np.random.randint(0, 2, (8, 3))
print(np.unique(x, axis=0))
```

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 

(**hint**: np.einsum)

```{python}
#使用einsum函数，我们可以使用爱因斯坦求和约定（Einstein summation convention）在NumPy数组上指定操作
A = np.random.uniform(0,1,10) # 均匀分布
B = np.random.uniform(0,1,10) # 均匀分布

np.einsum('i->', A) # 求和
np.einsum('i,i->i', A, B) # 矩阵相乘
np.einsum('i,i', A, B)    # 内积
np.einsum('i,j->ij', A, B)    # 外积
```

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 

(**hint**: np.cumsum, np.interp)

```{python}
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)
```

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 

(**hint**: np.logical\_and.reduce, np.mod)

```{python}
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])

n = 4
print(np.mod(X, 1) == 0)
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)

# np.mod(X,1) 找出整数，
# axis =-1 表示最后一个维度
M = (X.sum(axis=-1) == n)
# 在最后一个维度上和为4
print(X[M])
```

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 

(**hint**: np.percentile)

```{python}
X = np.random.randn(100)
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)
```